// The Stats tab: the mirror. Every number here comes from the repo's own JSON,
// generated by tools/engine_review.py and tools/analyze.py. Nothing is estimated.

import { ratingChart, barChart, stackedBar, histogram, sparkColumns } from './charts.js';

const pct = (n) => `${n.toFixed(1)}%`;

function tile(value, label, note, tone = '') {
  return `<div class="tile ${tone}">
    <div class="tile-value">${value}</div>
    <div class="tile-label">${label}</div>
    ${note ? `<div class="tile-note">${note}</div>` : ''}
  </div>`;
}

function section(title, subtitle) {
  const s = document.createElement('section');
  s.className = 'stat-section';
  s.innerHTML = `<h3>${title}</h3>${subtitle ? `<p class="sub">${subtitle}</p>` : ''}`;
  return s;
}

export function renderStats(root, data) {
  const s = data.stats;
  root.innerHTML = '';

  // ------------------------------------------------------------- headline tiles
  const head = document.createElement('div');
  head.className = 'tiles';
  head.innerHTML = [
    tile(s.rating_now, 'rapid now', `peak ${s.rating_peak} on ${s.rating_peak_date}`),
    tile(s.blunders_per_game.toFixed(1), 'blunders per game', `${s.blunders_total} in ${s.moves_analyzed} moves, depth 16`, 'bad'),
    tile(pct(s.winning_blunder_share), 'blunders from winning positions', `${s.winning_blunders} of them, ${s.winning_blunders_unconverted} in games then not won`, 'bad'),
    tile(pct(s.snap_share), 'moves under 3 seconds', `${s.snap_moves} of ${s.timed_moves} timed moves`, 'bad'),
    tile(s.accuracy_mean.toFixed(1), 'mean accuracy', `Lichess formula — reads +${s.accuracy_offset.toFixed(1)} vs chess.com`),
    tile(`${s.median_clock_left}%`, 'median clock left when losing', `${s.clock_rich_losses} of ${s.losses} losses had over half the clock`, 'bad'),
  ].join('');
  root.append(head);

  // -------------------------------------------------------------- rating curve
  const rating = section(
    'Rating',
    `${s.rapid_games_all} rapid games since ${s.first_game_date}. The goal line is 1600.`,
  );
  rating.append(ratingChart(data.rating_series, {
    goal: 1600,
    peak: { t: s.rating_peak_t, r: s.rating_peak },
  }));
  root.append(rating);

  // ----------------------------------------------------- the counterintuitive one
  const think = section(
    'Blunder rate by think time',
    'The result that matters most here: blundering gets <em>more</em> likely the longer the think. ' +
    'That is not a case for moving faster — it is Heisman\'s quiescence error, stopping calculation ' +
    'one move short in exactly the positions that punish it. The sub-5-second band is a different ' +
    'problem with the same fix.',
  );
  think.append(barChart(
    data.charts.think_time.map((b) => ({
      label: b.label,
      value: Number((b.rate * 100).toFixed(1)),
      note: `${b.blunders} / ${b.moves}`,
      highlight: b.rate >= 0.15,
    })),
  ));
  root.append(think);

  // ------------------------------------------------------------------- by phase
  const phase = section(
    'Blunder rate by phase',
    'The middlegame is the syllabus — it holds 78% of everything that goes wrong.',
  );
  phase.append(barChart(
    data.charts.phase.map((b) => ({
      label: b.label,
      value: Number((b.rate * 100).toFixed(1)),
      note: `${b.blunders} / ${b.moves}`,
      highlight: b.label === 'middlegame',
    })),
  ));
  root.append(phase);

  // --------------------------------------------------------- move classification
  const cls = section(
    'Every move, classified',
    `${s.moves_analyzed} of your moves at depth 16. Evals are clamped at ±1000cp, so nothing here runs away.`,
  );
  cls.append(stackedBar(data.charts.classification.map((c) => ({
    label: c.label, value: c.n, cls: `slice-${c.label}`,
  }))));
  root.append(cls);

  // ---------------------------------------------------------------- over time
  if (data.charts.by_month?.length) {
    const trend = section(
      'Blunders per game, by month',
      'Whether the habit work is landing. Hover a column for the game count behind it.',
    );
    trend.append(sparkColumns(data.charts.by_month.map((m) => ({
      label: m.month, value: Number(m.per_game.toFixed(1)), n: m.games,
    }))));
    root.append(trend);
  }

  // ------------------------------------------------------------------- clock
  if (data.charts.clock_left?.length) {
    const clock = section(
      'Clock remaining when you lost',
      `Median ${s.median_clock_left}%. A loss with half the clock unspent is a loss you had the ` +
      `time to prevent — this is the chart the 15|10 switch is meant to move.`,
    );
    clock.append(histogram(data.charts.clock_left, { xLabel: 'share of base time still on the clock' }));
    root.append(clock);
  }

  // ------------------------------------------------------------------ motifs
  const motifs = section(
    'What the blunders give away',
    'The right-hand column is the discipline tell: endgame and mate blunders are overwhelmingly ' +
    'rushed, which is a habit problem. More puzzles will not fix those.',
  );
  const table = document.createElement('table');
  table.className = 'data-table';
  table.innerHTML = `
    <thead><tr><th>Motif</th><th class="num">Blunders</th><th class="num">Share</th>
    <th class="num">Played under 5s</th></tr></thead>
    <tbody>${data.charts.motifs.map((m) => `
      <tr><td>${m.motif}</td><td class="num">${m.n}</td><td class="num">${pct(m.share * 100)}</td>
      <td class="num ${m.rushed_share > 0.4 ? 'flag' : ''}">${m.rushed} (${pct(m.rushed_share * 100)})</td></tr>`).join('')}
    </tbody>`;
  motifs.append(table);
  root.append(motifs);

  // ----------------------------------------------------------------- provenance
  const prov = document.createElement('p');
  prov.className = 'provenance';
  prov.innerHTML =
    `Game statistics generated <strong>${data.meta.stats_generated}</strong> from ` +
    `${s.total_games} games. Engine review generated <strong>${data.meta.engine_generated}</strong> ` +
    `at depth 16 over ${s.games_reviewed} rapid games. The two dates differ; the numbers are not ` +
    `from the same run.`;
  root.append(prov);
}
